import type { Metadata } from "next";
import "./globals.scss"
import Navhome from "@/componentes/Navhome";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{

  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Navhome/>
        {children}
      </body>
    </html>
  );
}
